snok/install-poetry

.github/workflows/test.yml
README.md

Changes example workflows, so they're not caching the root project installation.
Resolves #19.

Update example workflows

---

README.md
action.yml
pyproject.toml

We initially curled resources into the project root. This takes advantage of the mktemp function to make sure that we never accidentally delete something we're not supposed to because of name collisions. 
Haven't tested if there was a problem to begin with, but this change seems positive regardless.

Download remote files to temp directories to prevent collisions

---

.github/workflows/test.yml
README.md
action.yml
pyproject.toml
scripts/v1.2/main.sh

Poetry just released 1.2.0a1, [here](https://github.com/python-poetry/poetry/releases/tag/1.2.0a1).
From the changes, the most notable for us seems to be that they are deprecating the `get-poetry.py` script. This PR therefore switches to using the `install-poetry.py` script instead.

Add support for changes introduced in v1.2.0a1

---

.github/workflows/test.yml

Test against Python 3.10.0-alpha.5

---

.github/workflows/test.yml
README.md
action.yml

Sets the default value for `version` to be `latest`. If the version input has not been set, we will install Poetry without the `--version` argument, meaning the latest version is installed.
This should remove the need to update the default version every time Poetry makes a release 🙂

Make 'latest' the version default

---

.github/workflows/test.yml
action.yml

Related to https://github.com/snok/install-poetry/issues/54 and https://github.com/snok/install-poetry/issues/55.
After removing the quoted inputs, I added this test case:
```yaml
test-setting-non-default-settings:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- uses: ./
with:
version: 1.1.7
virtualenvs-create: false
virtualenvs-in-project: true
virtualenvs-path: ~/.cache/virtualenvs
installer-parallel: false
- run: |
source .github/scripts/assert.sh
assert_in  "1.1.7"                            "$(poetry --version)"
assert_in  "false"                            "$(poetry config virtualenvs.create)"
assert_in  "true"                             "$(poetry config virtualenvs.in-project)"
assert_in  "/home/runner/.cache/virtualenvs"  "$(poetry config virtualenvs.path)"
assert_in …
```

Unquote action config arguments

---

.github/workflows/test.yml
README.md
action.yml

Accept additional options from the user that are directly passed to poetry when installing it.
This will allow to install directly from github or use any of the other options accepted by [poetry's installer script](https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py).
This closes #59.

Accept additional options to pass to poetry 

---

README.md

Virtual environments are heavily Python version specific, and it doesn't
really make sense to share the cache between different Python versions.

Instruct to use the Python version as part of the venv cache key

---

.pre-commit-config.yaml

Thank you for creating this action.
Looking over it I realized that one pre-commit-hook is defined two times.

Remove duplicate pre-commit-hook

---

main.sh

https://github.com/python-poetry/install.python-poetry.org
By updating the URL we could potentially be affected by bugs introduced upstream, but using the official installation-script URL still seems like the right choice.

chore: Update installation script URL

---

.github/workflows/test.yml

* Added latest stable version 1.1.14
* Set latest poetry to 1.1.14
* Added pre-releases 1.2.0b1, 1.2.0b2, 1.2.0b3

Update to latest poetry versions (July 2022)

---

.pre-commit-config.yaml
poetry.lock
pyproject.toml

Updates the pyproject.toml Python version to 3.7 and updates pre-commit hooks. This doesn't really impact the github action.

Drop Python version 3.6

---

.editorconfig
.github/scripts/assert.sh
.pre-commit-config.yaml
main.sh
scripts/v1.1/main.sh
scripts/v1.2/main.sh

Adds `shfmt` and `shellcheck` to our linter setup. Only the `${INSTALLATION_ARGUMENTS}` call in `main.sh:20` looks like it cannot be formatted according to shellcheck, so I've added ignore statements for those. This mainly re-formats the old script files. 
Also sets `set -eo pipefail` to make the action error properly. The "command poetry does not exist" output for when the installation failed is not very user friendly.

Lint shell scripts

---

.github/workflows/test.yml

Adds back Python 3.8 and 3.9, and updates the 3.11 release candidate. Poetry 1.2.2 was also just released.

Update Python and Poetry test matrix versions

---

main.sh

Removes windows-only logic from the action. This seems not to be needed.

Remove windows-only logic from the action

---

.github/workflows/test.yml
main.sh

Adds the Python matrix to the non-default settings test. This would have uncovered the issue from #94. Then it resolves #94 by avoiding the official installation script for Windows targets. 
A few things to consider:
- It would have been nice to limit the logic to Windows for Python <= 3.8, but we cannot reliably know what Python version is active, can we? I believe using `setup-python` after this action works most of the time, if not all of the time.
- This just reverts to the old installation script. Are there any reasons to consider using a newer version of it?

Resolve windows 3.8 issue

---

README.md

I got an error running the example code:
Version 3.1 was not found in the local cache
Error: Version 3.1 with arch x64 not found
It basically treated the python version 3.10 as a float which is equivalent to 3.1 which cannot be found. I added the quotation marks to make sure it is treated as a string.

added quotes around python version in README examples

---

.github/workflows/test.yml

- fixed usage of `set-output`, see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Clean up the check-latest step

---

.github/workflows/lint.yml
.github/workflows/test.yml

https://docs.python.org/3.11/whatsnew/3.11.html
> Python 3.11 is between 10-60% faster than Python 3.10. On average, we measured a 1.25x speedup on the standard benchmark suite.

GitHub Actions: Upgrade to Python 3.11 production release

---

README.md

I was setting up your action with coverage and came across this [deprecation](https://github.com/codecov/codecov-action#%EF%B8%8F--deprecation-of-v1).

codecov/codecov-action@v1 is deprecated; v3 is now recommended

---

main.sh

Respect $POETRY_HOME if set

---

.github/workflows/test.yml
README.md
pyproject.toml

#135 
Poetry no longer supports Python 3.7. Removed 3.7 from tests and toml

RE: #135 Python 3.7 Not Supported

---

main.sh

Thanks for the amazing GitHub Action! 
This PR removes `curl` usage from the script and replaces it with `python3`. Many hosted GitHub Action runners don't have `curl` by default, so they are required to install it before using this action. This PR ensures that the installation of `curl` is not needed.

Remove `curl` dependency

---

README.md

In #150, I described a usecase were caching the Poetry installation was causing the dependency cache step to break when the `.lock` was updated.
In summary, if some action used a cached poetry install (skips running `snok/install-poetry`), the configurations set in `with` would not be done, which caused any new dependency installs to not be cached, as Poetry by default installs venvs not in the `.venv` path (so the cache step can't find the `.venv` directory to cache).
This PR adds a section in the docs to clarify this and guide users to a fix.

Improve cache Poetry install instructions

---

main.sh

**Problem:** A recent change https://github.com/snok/install-poetry/pull/153 removed `curl` usage from the script and replaced it with `python`. The justification is that script already relies on Python being present. However, it relies specifically on `python3`, not `python`. As reported in https://github.com/snok/install-poetry/issues/158, calling `python` errors out on some setups:
```
/home/runner/_work/_actions/snok/install-poetry/v1/main.sh: line 6: python: command not found
```
**Solution:** Use `python3` instead of `python`.

Use `python3` instead of `python`
